### ISSUE TITLE
Report hipscat - Full

### ISSUE THREAD

**Issue by gschwend** [linea-it/pzserver#140]
**Ideia principal: texto simples reportando os resultados das rodadas de hipscat import e x-matching, com informações detalhadas sobre a rodada (tamanho dos arquivos, márquinas usadas, memória, CPUs, etc.)**

Draft aqui: https://docs.google.com/document/d/1-_TIuTRyTS9TavFcyUd5kFYR8gc0CpW2muzgPY3Y8DA/edit?usp=sharing 

```[tasklist]
### Tasks
- [ ] https://github.com/linea-it/pz-compute/issues/108
- [ ] https://github.com/linea-it/pzserver/issues/116
- [ ] https://github.com/linea-it/pzserver/issues/118
- [ ] https://github.com/linea-it/pzserver/issues/139
- [ ] https://github.com/linea-it/pzserver/issues/137
- [ ] https://github.com/linea-it/pzserver/issues/138
- [ ] https://github.com/linea-it/pzserver/issues/117
- [ ] https://github.com/linea-it/pzserver/issues/131
- [ ] https://github.com/linea-it/pzserver/issues/120
- [ ] https://github.com/linea-it/pzserver/issues/124
- [ ] https://github.com/linea-it/pzserver/issues/141
- [ ] https://github.com/linea-it/pzserver/issues/133
- [ ] https://github.com/linea-it/pzserver/issues/119
- [ ] https://github.com/linea-it/pzserver/issues/135
- [ ] https://github.com/linea-it/pzserver/issues/136
- [ ] https://github.com/linea-it/pzserver/issues/125
- [x] Write the conclusion
- [x] share scripts used to produce results and make plots
```

**Comment by luigilcsilva** [comment]
Os scripts podem ser encontrados [neste link](https://github.com/linea-it/pz-compute/tree/report_hats/doc/report_hats). Acabei subindo para o repositório do pz-compute, mas depois posso subir para o repositório do pz-server, abrir o PR e associar a essa issue.

**Comment by luigilcsilva** [comment]
Os notebooks agora estão no repositório do pzserver, em https://github.com/linea-it/pzserver/tree/report_hats/docs/notebooks/report_hats

O report se encontra em https://docs.google.com/document/d/1-_TIuTRyTS9TavFcyUd5kFYR8gc0CpW2muzgPY3Y8DA/edit?tab=t.0#heading=h.ijqcuwdje1n0

Tudo está pronto para revisão final, para eventuais correções ou modificações.
