### ISSUE TITLE
update notebook pzserver lib e gerar RST com resultados para alimentar a pág de documentação

### ISSUE THREAD

**Issue by gschwend** [linea-it/pzserver#80]
```[tasklist]
### Tasks
- [x] add example of upload from the lib
- [ ] https://github.com/linea-it/pzserver/issues/87
- [x] add path to the new RST files to the sphinx documentation
```

**Comment by gschwend** [comment]
duplicated
